### ISSUE TITLE
artisan generate:scaffold not working correctly

### ISSUE THREAD

**Issue by janareit** [pingpong-labs/generators#2]
```artisan generate:scaffold``` is giving this error when its trying to generate view resources.

```
[2015-05-29 10:52:57] local.ERROR: exception 'ErrorException' with message 'file_get_contents(C:\wamp\www\petkafy-promens\vendor\pingpong\generators/Stubs/C:\wamp\www\petkafy-promens\vendor\pingpong\generators\FormDumpers/../Stubs/form/text.stub): failed to open stream: Invalid argument' in C:\wamp\www\petkafy-promens\vendor\pingpong\support\Stub.php:104
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_get_conten...', 'C:\\wamp\\www\\pet...', 104, Array)
#1 C:\wamp\www\petkafy-promens\vendor\pingpong\support\Stub.php(104): file_get_contents('C:\\wamp\\www\\pet...')
#2 C:\wamp\www\petkafy-promens\vendor\pingpong\support\Stub.php(120): Pingpong\Support\Stub->getContents()
#3 C:\wamp\www\petkafy-promens\vendor\pingpong\generators\FormDumpers\StubTrait.php(76): Pingpong\Support\Stub->render()
#4 C:\wamp\www\petkafy-promens\vendor\pingpong\generators\FormDumpers\FieldsDumper.php(50): Pingpong\Generators\FormDumpers\FieldsDumper->getStub('string', 'name')
#5 C:\wamp\www\petkafy-promens\vendor\pingpong\generators\FormGenerator.php(68): Pingpong\Generators\FormDumpers\FieldsDumper->render()
#6 C:\wamp\www\petkafy-promens\vendor\pingpong\generators\FormGenerator.php(45): Pingpong\Generators\FormGenerator->renderFromFields()
#7 C:\wamp\www\petkafy-promens\vendor\pingpong\generators\ScaffoldGenerator.php(272): Pingpong\Generators\FormGenerator->render()
#8 C:\wamp\www\petkafy-promens\vendor\pingpong\generators\ScaffoldGenerator.php(250): Pingpong\Generators\ScaffoldGenerator->generateView('index')
#9 C:\wamp\www\petkafy-promens\vendor\pingpong\generators\ScaffoldGenerator.php(384): Pingpong\Generators\ScaffoldGenerator->generateViews()
#10 C:\wamp\www\petkafy-promens\vendor\pingpong\generators\Console\ScaffoldCommand.php(34): Pingpong\Generators\ScaffoldGenerator->run()
#11 [internal function]: Pingpong\Generators\Console\ScaffoldCommand->fire()
#12 C:\wamp\www\petkafy-promens\vendor\laravel\framework\src\Illuminate\Container\Container.php(523): call_user_func_array(Array, Array)
#13 C:\wamp\www\petkafy-promens\vendor\laravel\framework\src\Illuminate\Console\Command.php(115): Illuminate\Container\Container->call(Array)
#14 C:\wamp\www\petkafy-promens\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(257): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\wamp\www\petkafy-promens\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\wamp\www\petkafy-promens\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\wamp\www\petkafy-promens\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Pingpong\Generators\Console\ScaffoldCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 C:\wamp\www\petkafy-promens\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\wamp\www\petkafy-promens\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(94): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\wamp\www\petkafy-promens\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main} 
```

how could I fix it?

**Comment by janareit** [comment]
I can fix it for view cenerator by changing `Stub.php` from:

```
    public function getPath()
    {
        return static::$basePath . $this->path;
    }
```

to

```
    public function getPath()
    {
        return $this->path;
    }
```

However by doing this I brake model generator. So problem must be $this->path gets full path somewhere when arriving to views generation I guess...

**Comment by janareit** [comment]
Now a fix to get both generators working:

add `Stub::setBasePath('');` to StubTrait.php

```
        Stub::setBasePath('');

        return Stub::create(__DIR__ . '/../Stubs/form/' . $type . '.stub', [
            'name' => $name,
            'label' => ucwords($name),
        ])->render();
```
